// PLACEHOLDER - not a real Firebase project.
//
// This file is normally generated by the FlutterFire CLI:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// It is checked in with placeholder values so the project compiles out of the
// box while running on the local demo backend (`Backend.demo`). Running
// `flutterfire configure` overwrites it with your real project's values.
//
// The Android `appId` below is real - it is the app CI ships builds to via
// Firebase App Distribution (see .github/workflows/android-distribute.yml).
// The API keys and project id are still placeholders.
//
// Nothing here is read unless `AppConfig.instance.backend == Backend.firebase`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Placeholder [FirebaseOptions] for each supported platform.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  /// Set to `true` by `flutterfire configure`; guards against silently
  /// initialising Firebase with placeholder credentials.
  static const bool isConfigured = false;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      TargetPlatform.macOS => ios,
      _ => throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for $defaultTargetPlatform. '
          'Run `flutterfire configure` to add it.',
        ),
    };
  }

  /// Project number taken from the registered Android app ID. The rest of the
  /// values still have to come from `flutterfire configure`.
  static const String messagingSenderId = '846777623577';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_WEB_API_KEY',
    appId: '1:846777623577:web:0000000000000000000000',
    messagingSenderId: messagingSenderId,
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    authDomain: 'REPLACE_WITH_YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'REPLACE_WITH_YOUR_PROJECT_ID.appspot.com',
  );

  /// The real Android app, registered for CI distribution. Only [appId] and
  /// [messagingSenderId] are known here; App Distribution needs nothing more,
  /// but running the app against Firebase needs the API key and project id too.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_ANDROID_API_KEY',
    appId: '1:846777623577:android:8fefdbc82283d5ec6a7688',
    messagingSenderId: messagingSenderId,
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_IOS_API_KEY',
    appId: '1:846777623577:ios:0000000000000000000000',
    messagingSenderId: messagingSenderId,
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.suthahar.foodDeliveryApp',
  );
}
