// PLACEHOLDER - not a real Firebase project.
//
// This file is normally generated by the FlutterFire CLI:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// It is checked in with placeholder values so the project compiles out of the
// box while running on the local demo backend (`Backend.demo`). Running
// `flutterfire configure` overwrites it with your real project's values.
//
// Nothing here is read unless `AppConfig.instance.backend == Backend.firebase`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Placeholder [FirebaseOptions] for each supported platform.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  /// Set to `true` by `flutterfire configure`; guards against silently
  /// initialising Firebase with placeholder credentials.
  static const bool isConfigured = false;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      TargetPlatform.macOS => ios,
      _ => throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for $defaultTargetPlatform. '
          'Run `flutterfire configure` to add it.',
        ),
    };
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'grabbite-demo',
    authDomain: 'grabbite-demo.firebaseapp.com',
    storageBucket: 'grabbite-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_ANDROID_API_KEY',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'grabbite-demo',
    storageBucket: 'grabbite-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_IOS_API_KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'grabbite-demo',
    storageBucket: 'grabbite-demo.appspot.com',
    iosBundleId: 'com.suthahar.foodDeliveryApp',
  );
}
